alias mage-auth-staging="mage auth -e pcorp-use1 -n prx-ir-staging -N"
alias mage-auth-prod="mage auth -e pcorp-use1 -n prx-ir-prod -N"

alias sbot-logs="nomad alloc logs -f -job slack-pds-p0-automation-supportbot slack-pds-p0-automation-supportbot"
alias sbot-stop-prod="hashideploy client -j slack-pds-p0-automation-supportbot --namespace prx-ir-prod --mode stop"
alias sbot-stop-staging="hashideploy client -j slack-pds-p0-automation-supportbot --namespace prx-ir-staging --mode stop"
alias sbot-start-prod="hashideploy client -j slack-pds-p0-automation-supportbot --namespace prx-ir-prod --mode restart"
alias sbot-start-staging="hashideploy client -j slack-pds-p0-automation-supportbot --namespace prx-ir-staging --mode restart"

alias cronus-logs-local="docker logs -f cronus.palantir.pt | slslog --exclude metric.1"
alias cronus-logs="nomad alloc logs -f -job cronus cronus | slslog --exclude metric.1"
alias cronus-stop-prod="hashideploy client -j cronus --namespace prx-ir-prod --mode stop"
alias cronus-stop-staging="hashideploy client -j cronus --namespace prx-ir-staging --mode stop"
alias cronus-start-prod="hashideploy client -j cronus --namespace prx-ir-prod --mode restart"
alias cronus-start-staging="hashideploy client -j cronus --namespace prx-ir-staging --mode restart"

alias end-logs-local="docker logs -f endeavour.palantir.pt | slslog --exclude metric.1"
alias end-logs="nomad alloc logs -f -job endeavour endeavour | slslog --exclude metric.1"
alias end-stop-prod="hashideploy client -j endeavour --namespace prx-ir-prod --mode stop"
alias end-stop-staging="hashideploy client -j endeavour --namespace prx-ir-staging --mode stop"
alias end-start-prod="hashideploy client -j endeavour --namespace prx-ir-prod --mode restart"
alias end-start-staging="hashideploy client -j endeavour --namespace prx-ir-staging --mode restart"

alias hermes-logs-local="docker logs -f hermes.palantir.pt | slslog --exclude metric.1"
alias hermes-logs="nomad alloc logs -f -job hermes hermes | slslog --exclude metric.1"
alias hermes-stop-prod="hashideploy client -j hermes --namespace prx-ir-prod --mode stop"
alias hermes-stop-staging="hashideploy client -j hermes --namespace prx-ir-staging --mode stop"
alias hermes-start-prod="hashideploy client -j hermes --namespace prx-ir-prod --mode restart"
alias hermes-start-staging="hashideploy client -j hermes --namespace prx-ir-staging --mode restart"

alias piom-logs-local="docker logs -f pds-issue-object-manager.palantir.pt | slslog --exclude metric.1"
alias piom-logs="nomad alloc logs -f -job pds-issue-object-manager pds-issue-object-manager | slslog --exclude metric.1"
alias piom-stop-prod="hashideploy client -j pds-issue-object-manager --namespace prx-ir-prod --mode stop"
alias piom-stop-staging="hashideploy client -j pds-issue-object-manager --namespace prx-ir-staging --mode stop"
alias piom-start-prod="hashideploy client -j pds-issue-object-manager --namespace prx-ir-prod --mode restart"
alias piom-start-staging="hashideploy client -j pds-issue-object-manager --namespace prx-ir-staging --mode restart"